mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.jianwoo.eshop.manage.entity
#  config-location: classpath:mybatis/SqlMapConfig.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.99.103:3308/mymall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000ms
    host: 192.168.99.103
    port: 6380
server:
  port: 9005
dubbo:
  application:
    name: item-servier111
    qos-enable: true
    qos-port: 23532
    qos-accept-foreign-ip: false
